### ISSUE TITLE
pHidden ignores initial true value

### ISSUE THREAD

**Issue by sambaptista** [danielpdev/angular-particle-effect-button#3]
pHidden works fine when changing from a false value into a true one, but when it's initialized with `true`, the target is still visible.

But I'm not sure what should be the result : 

* the target disappears with animation when initializing
* the target is hidden when initialized without disappearing animation.

I think the second option is more compliant with expectations.

**Comment by danielpdev** [comment]
I also have some questions on how `angular-particle-effect-button` should behave when `pHidden` is initialized with `true` value
- the target disappears with animation when initializing
This will be the proper way of doing it because the meaning of `pHidden` is to trigger the animation.
However, I could add a new property for the cases when you just need it to be hide and don't perform animation. 

- the target is hidden when initialized without disappearing animation.
What will happen if after a while you switch the `pHidden` to `false` again? It should trigger the appearing animation?

If you just want to be hidden and don't perform any animations, why don't you just use the NgIf directive?

Hope it helps,
Thanks

**Comment by sambaptista** [comment]
> If you just want to be hidden and don't perform any animations, why don't you just use the NgIf directive?

The point of this issue is for sure to keep animations as usual, but always have an logic initial behavior.

After a little more reflexion there is what I think to be the better behavior :

1) Component initialises with pHidden: true => the component is hidden without disappearing animation
2) Change to pHidden: false =>  Appearing animation
3) Change to pHidden: true again =>Disappearing animation
4) Reproduce step 2
5) Reproduce step 3
6) etc...

I can give any help and try to produce a pull request if you provide some tips about where to start.

**Comment by sambaptista** [comment]
In case of doubt, there is a little additional thinking :

When a component initialises with `pHidden=false`, that mean it's visible but it doesn't display with an appearing animation at start. Then it uses animation for each further visibility change.

The same behavior should be reproduced when the component initializes with `pHidden=true`: It starts hidden, without disappearing animation at start. Then it uses animation for each further visibility change.
